plugins:
  - rubocop-rspec
  - rubocop-rake
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Style/Documentation:
  Enabled: false
